[project]
name = "fantasyapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.0",
    "scipy==1.11.3",
    "requests==2.32.3",
    "tqdm==4.67.1",
]
